app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/d', 'PacientController@store');
/*
Route::post('/test/save', ['as' => 'save-date',
                           'uses' => 'DateController@showDate', 
                            function () {
                                return '';
                            }]);
*/

/* 
Route::get('/test/datepicker', function () {
    return view('datepicker');
});
*/
 
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|

*/
/*Route::get('prueba',function()
    {
        $u=App\User::find(6)->admin();
        dd($u);

    });

Route::group(['middleware' => ['web','admin']], function () {
    //
});*/



//Route::get('specialty/j','SpecialityController@mostrar_id');
Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::model('users', App\User::class);
    Route::resource('users', 'UserController');
});

Route::resource('pacient','PacientController');

Route::get('a','UserController@show');

;

//Route::get('specialty/j','SpecialityController@mostrar_id');

Route::get('cita', function()
    {
        return view('citamedica.index');
    });
Route::get('cita/create', function()
    {
        return view('citamedica.create');
    });

Route::get('horario/create', function()
    {
        return view('horario.create');
    });



Route::get('especialidad/json','SpecialityController@dame_especialidades');
Route::group(['middleware' => ['web']], function () {
    Route::resource('especialidad','SpecialityController');

    
});

resources/views/especialidad/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(['route' => 'especialidad.store', 'method' => 'post', 'role' => 'form']) !!}

            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Crear una nueva especialidad</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('especialidad.index') }}"> ATRAS</a>
                    </div>
                </div>
            </div>



            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>error!</strong> usted debe ingresar una especialidad.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
           
                <div class="form-group">
                    {{ Form::label('name', 'nombre', ['class' => 'text-uppercase']) }}
                    {{ Form::text('name', null , ['class' => 'form-control text-uppercase']) }}
                   
                </div>
                
                <div class="form-group">
                    <a class="btn btn-xs btn-danger" href="{{ url('users') }}">CANCELAR</a>
                    <button class="btn btn-success btn-xs">GUARDAR</button>
                </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>

@endsection

resources/views/especialidad/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
           
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('especialidad.index') }}"> ATRAS</a>
                    </div>
                </div>
            </div>
            
            @if(count($errors)>0)
            <div class="alert alert-danger">
                <strong>lo sentimos!!!</strong>ha ocurrido un error en la editacion.<br><br>
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                </ul>
            </div>
            @endif


            {!! Form::model($especialidad, ['method' => 'PATCH','route' => ['especialidad.update', $especialidad->id]]) !!}
                <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>nombre:</strong>
                            {!! Form::text('name', null, array('placeholder' => 'nombres','class' => 'form-control')) !!}
                        </div>
                    </div>

                    
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
 

@endsection

resources/views/especialidad/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary btn-xs" href="{{ url('especialidad/create') }}">NUEVA ESPECIALIDAD</a>


             @include('partials.message')

            @if(count($especialidades) > 0)
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>NOMBRE</th>
                        <th>OPCIONES</th>                          
                    </tr>


                    
                </thead>
            
                <tbody>
                    @foreach($especialidades as $esp)
                        <tr>
                            <td>{{ $esp->id }}</td>
                            <td>{{ $esp->name }}</td>
                            <td>
                                <a class="btn btn-info" href="{{ route('especialidad.show',$esp->id) }}">Ver</a>
                                <a class="btn btn-primary" href="{{ route('especialidad.edit',$esp->id) }}">Editar</a>
                                {!! Form::open(['method' => 'DELETE','route' => ['especialidad.destroy', $esp->id],'style'=>'display:inline']) !!}
                                {!! Form::submit('eliminar', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                           
                        </tr>


                        
                    @endforeach
                </tbody>




            </table>
            
            
            @else
                <div class="alert alert-info">
                    <h4>INFORMACION</h4>no existe ninguna especialidad creada
                </div>
            @endif
            
        </div>
    </div>
</div>
{!! $especialidades->render() !!}
@endsection

resources/views/especialidad/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
           
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('especialidad.index') }}"> ATRAS</a>
                    </div>
                </div>
            </div>


            <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>numero:</strong>
                            {{ $especialidad->id }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>nombre:</strong>
                            {{ $especialidad->name }}
                        </div>
                    </div>

                </div>

@endsection