app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/d', 'PacientController@store');
/*
Route::post('/test/save', ['as' => 'save-date',
                           'uses' => 'DateController@showDate', 
                            function () {
                                return '';
                            }]);
*/

/* 
Route::get('/test/datepicker', function () {
    return view('datepicker');
});
*/
 
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|

*/
/*Route::get('prueba',function()
    {
        $u=App\User::find(6)->admin();
        dd($u);

    });

Route::group(['middleware' => ['web','admin']], function () {
    //
});*/



//Route::get('specialty/j','SpecialityController@mostrar_id');
Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::model('users', App\User::class);
    Route::resource('users', 'UserController');
});

Route::resource('pacient','PacientController');

Route::get('a','UserController@show');

;

//Route::get('specialty/j','SpecialityController@mostrar_id');

Route::get('cita', function()
    {
        return view('citamedica.index');
    });
Route::get('cita/create', function()
    {
        return view('citamedica.create');
    });

Route::get('horario/create', function()
    {
        return view('horario.create');
    });



Route::get('especialidad/json','SpecialityController@dame_especialidades');
Route::group(['middleware' => ['web']], function () {
    Route::resource('especialidad','SpecialityController');

    
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password','type'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function people()
    {
        return $this->hasOne('App\people', 'id', 'people_id');
    }
    #establecemos la relaion con el modelo Role 

    public function admin()
    {
        return $this->type === "admin";
    }
    public function medical_speciality()
    {
        return $this->hasOne(Speciality::class);
    } 

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\People;
use App\User;
use Illuminate\Http\Request;
use App\Speciality;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\UserRequest;

use DB;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('people')->paginate(14);
        //$users = DB::table('users')->join('people', 'users.people_id', '=', 'people.id')
          //  ->select('users.*', 'people.*')
           // ->paginate(14);
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $especialidades=Speciality::all();
        $people = new People;
        $people->name       =   $request->name;
        $people->firstname  =   $request->firstname;
        $people->lastname   =   $request->lastname;
        if($people->save())
        {
            $user = new User;
            $user->username =   $request->username;
            $user->email    =   $request->email;
            $user->password =   bcrypt($request->password);
            $user->type     =   $request->type;
            //$user->medical_speciality_id = null;

            if($user->type =='medico')
            {
                $user->medical_speciality_id=$request['medical_speciality_id'];
            }
            
            
           
            if($people->user()->save($user)){
                   

                Session::flash('msg_title', 'Exito');
                Session::flash('msg_description', 'se ha creado un nuevo usuario');
                Session::flash('msg_type', 'success');
            }
            else{
                Session::flash('msg_title', 'error');
                Session::flash('msg_description', 'los sentimos no pudo registrase un nuevo usuario');
                Session::flash('msg_type', 'danger');
            }
        }

        return redirect('users');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       // dd($id->id);
        /*$users = DB::table('users')
            ->join('people', 'users.id', '=', 'people.id')
            ->select('users.*', 'people.*')
            ->get();

        return view('user.show',  compact('users'));
        
        $users = User::find($id)
                        ->with('people');
        return view('user.show', compact('users'));






        $users = DB::table('people')->find($id)
            ->join('users', 'people.id', '=', 'users.people_id')
            ->select('people.*', 'users.*')
            ->get();
        return view('user.show', compact('users')); */


        $users = $id;
        return view('user.show',compact('users'));
       

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user->people;

        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        return redirect('users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(['route' => 'users.store', 'method' => 'post', 'role' => 'form']) !!}
                @include('partials.errors')
                
                <div class="form-group">
                    {{ Form::label('name', 'nombres', ['class' => 'text-uppercase']) }}
                    {{ Form::text('name', old('name'), ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('firstname', 'apellido paterno', ['class' => 'text-uppercase']) }}
                    {{ Form::text('firstname', old('firsname'), ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('lastname', 'apellido materno', ['class' => 'text-uppercase']) }}
                    {{ Form::text('lastname', old('lastname'), ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('username', 'nombre de usuario', ['class' => 'text-uppercase']) }}
                    {{ Form::text('username', old('username'), ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('email', 'E-mail', ['class' => 'text-uppercase']) }}
                    {{ Form::email('email', old('email'), ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('password', 'Contraseña', ['class' => 'text-uppercase']) }}
                    {{ Form::password('password', null, ['class' => 'form-control']) }}
                </div>
                <div>
                    {{ Form::label('type', 'TIPO DE USUARIO',['for' => 'type'])}}
                    {{ Form::select('type', array('admin'=>'ADMINISTRADOR', 'medico'=>'MEDICO', 'fichaje'=>'FICHAJE', 'farmaceutica'=>'FARMACEUTICA'),null, ['id' => 'type', 'class' => 'form-control text-uppercase']) }}
                </div>
                <div id="myajax">
                   
                     <input name='medical_speciality_id'/>
                    
                </div>
               
                <div class="form-group">
                    <a class="btn btn-danger" href="{{ url('users') }}">CANCELAR</a>
                    <button class="btn btn-success ">GUARDAR</button>
                </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {!! Form::model($user, ['route' => ['users.update' => $user], 'method' => 'PUT', 'role' => 'form']) !!}

                <div class="form-group">
                    {{ Form::label('name', 'nombres', ['class' => 'text-uppercase']) }}
                    {{ Form::text('name', $user->people->name, ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('firstname', 'apellido paterno', ['class' => 'text-uppercase']) }}
                    {{ Form::text('firstname', $user->people->firstname, ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('lastname', 'apellido materno', ['class' => 'text-uppercase']) }}
                    {{ Form::text('lastname', $user->people->lastname, ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('username', 'nombre de usuario', ['class' => 'text-uppercase']) }}
                    {{ Form::text('username', $user->username, ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('email', 'E-mail', ['class' => 'text-uppercase']) }}
                    {{ Form::email('email', $user->email, ['class' => 'form-control text-uppercase']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('password', 'Contraseña', ['class' => 'text-uppercase']) }}
                    {{ Form::password('password', null, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <a class="btn btn-xs btn-danger" href="{{ url('users') }}">CANCELAR</a>
                    <button class="btn btn-success btn-xs">GUARDAR</button>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary btn-xs" href="{{ url('users/create') }}">NUEVO USUARIO</a>

            @include('partials.message')

            @if(count($users) > 0)
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>NOMBRE</th>
                        <th>APELLIDO</th>
                        <th>USERNAME</th>
                        <th>EMAIL</th>
                        <th>TIPO DE USUARIO</th>
                        <th>ESPECIALIDAD</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->people->name }}</td>
                            <td>{{ $user->people->firstname }} {{ $user->people->lastname }}</td>
                            <td>{{ $user->username }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->type }}</td>
                            <th>{{ $user->medical_speciality_id}}</th>
                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('users.show', $user->id) }}" title="ver usuario">Ver</a>
                                <a class="btn btn-warning btn-xs" href="{{ route('users.edit', ['id' => $user->id]) }}" title="Editar usuario">Editar</a>
                                <a class="btn btn-danger btn-xs" href="{{ route('users.destroy', ['id' => $user->id]) }}" title="Eliminar usuario">Eliminar</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $users->links() !!}
            @else
                <div class="alert alert-info">
                    <h4>INFORMACION</h4>No existe ni un usuario registrado en el sistema.
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
           
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('users.index') }}"> ATRAS</a>
                    </div>
                </div>
            </div>


            <div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $users->people->name }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>nombre:</strong>
                            {{ $users->username }}
                        </div>
                    </div>

                     



            </div>

@endsection